TodoItem.create!(name: "Buy a horse")
TodoItem.create!(name: "Kill santa")
TodoItem.create!(name: "Hijak a plane")
TodoItem.create!(name: "Begin potty training")
TodoItem.create!(name: "Go to the dentist")
TodoItem.create!(name: "Drive to England")
TodoItem.create!(name: "Burn a cristmas goat")